swagger: "2.0"
info:
  description: "This is the documentation of the pastepwn API. You can find out more about Pastepwn on [GitHub](https://github.com/d-Rickyy-b/pastepwn)."
  version: "1.0.0"
  title: "Pastepwn API"
  contact:
    email: "pastepwn@rickyy.de"
  license:
    name: "MIT"
    url: "https://github.com/d-Rickyy-b/pastepwn/blob/master/LICENSE"
host: "pastepwn.rickyy.de"
basePath: "/"
tags:
- name: "pastes"
  description: "Everything about pastes"
schemes:
- "https"
paths:
  /pastes/{pasteId}:
    get:
      tags:
      - "pastes"
      summary: "Get the content of a specific paste by ID"
      description: ""
      operationId: "getPaste"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "pasteId"
        in: "path"
        description: "ID of the paste"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Paste"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Paste not found"
        405:
          description: "Validation exception"
  /pastes/findByDate:
    get:
      tags:
      - "pastes"
      summary: "Get pastes from within certain time frame"
      description: ""
      operationId: "addPet"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "fromDate"
        in: "body"
        description: "Starting date for the search"
        required: true
        schema:
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Paste"
        405:
          description: "Invalid input"

securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Tag:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
  Paste:
    type: "object"
    required:
    - "key"
    - "title"
    - "size"
    - "date"

    properties:
      key:
        type: "string"
        example: "0CeaNm8Y"
      title:
        type: "string"
        example: "Once we all know when we goto function"
      date:
        type: "integer"
        format: "int64"
        example: 1442911802
      expire:
        type: "integer"
        format: "int64"
        example: 1442998159
      syntax:
        type: "string"
        example: "java"
      user:
        type: "string"
        example: "admin"
      size:
        type: "integer"
        format: "int64"
        example: 890
      full_url:
        type: "string"
        example: "https://pastebin.com/0CeaNm8Y"
      scrape_url:
        type: "string"
        example: "https://scrape.pastebin.com/api_scrape_item.php?i=0CeaNm8Y"
      tags:
        type: "array"
        items:
          $ref: "#/definitions/Tag"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"